driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: debian-7.8
    run_list:
      - recipe[apt::default]
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[nscd::default]
    attributes:
      nscd:
        package: "unscd"
